- unique_name: test1  # functions also as prefix for found DBs if using patterns/continous discovery
  dbtype: postgres    # postgres|pgbouncer|postgres-continuous-discovery|patroni|patroni-continuous-discovery
  host: localhost
  port: 5432
  dbname: pgwatch2
  user: someuser
  password: somepass
  sslmode: disable
#  libpq_conn_str: postgresql://user@localhost:5432/postgres  # overrides single connect params. no pwd encryption possible
  stmt_timeout: 5
  is_superuser: false
  preset_metrics: minimal
  custom_metrics:    # if both preset and custom are specified, custom wins
  dbname_include_pattern:
  dbname_exclude_pattern:
  is_enabled: true
  group: default
  custom_tags:      # possibility for the user to add extra Influx tags
    env: prod
    cloud: aws
  sslrootcert: ''
  sslcert: ''
  sslkey: ''

- unique_name: test2
  dbtype: patroni-continuous-discovery
  host: localhost
  port: 5432
  dbname: ''
  user: postgres
  password:
  sslmode: disable
  host_config:    # host_config used only for dbtype=patroni|patroni-continuous-discovery currently
    dcs_type: etcd
    dcs_endpoints: ["http://localhost:2379"]
    scope: batman
    namespace: /service/
    username:
    password:
    ca_file:
    cert_file:
    cert_key:
    logs_glob_path: "/tmp/*.csv"
    logs_match_regex: ^(?P<log_time>.*?),"?(?P<user_name>.*?)"?,"?(?P<database_name>.*?)"?,(?P<process_id>\d+),"?(?P<connection_from>.*?)"?,(?P<session_id>.*?),(?P<session_line_num>\d+),"?(?P<command_tag>.*?)"?,(?P<session_start_time>.*?),(?P<virtual_transaction_id>.*?),(?P<transaction_id>.*?),(?P<error_severity>\w+),
  stmt_timeout: 5
  preset_metrics:
  custom_metrics:
    wal: 60
  dbname_include_pattern: (bar|postgres)
  dbname_exclude_pattern:
  is_enabled: false
